language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

env:
  - COMPOSER_ALLOW_XDEBUG=1

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: hhvm

before_script:
  - composer install --prefer-dist --dev
  - mkdir -p build/logs
  - ls -al

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml

after_success:
# Submit coverage report to Coveralls servers, see .coveralls.yml
 - travis_retry php coveralls.phar -v
# Submit coverage report to codecov.io
 - bash <(curl -s https://codecov.io/bash)
 
#after_failure:

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - vendor
  - $HOME/.cache/composer